SOURCE =Ejemplotipos.cpp
BIN =ejemplotipos.exe
OBJ =ejemplotipos.o
CXX =g++
CXXFLAGS = -std=c++17

$(BIN): $(OBJ)
	$(CXX) $(OBJ) -o $(BIN) $(CXXFLAGS)

$(OBJ): $(SOURCE)
	$(CXX) -c $(SOURCE) -o $(OBJ) $(CXXFLAGS)
